name: Generate Star History

on:
    workflow_dispatch:
    schedule:
        - cron: '0 11 * * *'  # Runs every day at midnight


jobs:
    generate-star-history:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: Generate Star History
              uses: narayann7/star-history-action@v1.0.6
              with:
                repos: 'ReSukiSU/ReSukiSU'
                readme: 'profile/README.md'